name: Create Environment

on:
  workflow_dispatch:
  # pull_request_target:
  #   types:
  #     - opened
  #     - reopened

jobs:
  dump_contexts:
    runs-on: ubuntu-22.04
    steps:
        - run: env
        - name: toJSON(inputs)
          run: echo '${{ toJSON(inputs) }}'
        - name: toJSON(github)
          run: echo '${{ toJSON(github) }}'
        - name: toJSON(env)
          run: echo '${{ toJSON(env) }}'
        - name: toJSON(vars)
          run: echo '${{ toJSON(vars) }}'
        - name: toJSON(secrets)
          run: echo '${{ toJSON(secrets) }}'
        - name: toJSON(job)
          run: echo '${{ toJSON(job) }}'
        - name: toJSON(steps)
          run: echo '${{ toJSON(steps) }}'
        - name: toJSON(runner)
          run: echo '${{ toJSON(runner) }}'
        - name: toJSON(strategy)
          run: echo '${{ toJSON(strategy) }}'
        - name: toJSON(matrix)
          run: echo '${{ toJSON(matrix) }}'
        - name: toJSON(needs)
          run: echo '${{ toJSON(needs) }}'
        - run: gh version

  createEnvironment:
    runs-on: ubuntu-22.04
    steps:
      - name: generate environment name
        run: |
          echo "ENV_NAME=dev-$(echo "$HEAD_REF" | sha1sum | cut -c1-8)"  \
          | tee $GITHUB_ENV
        env:
          HEAD_REF: ${{ github.head_ref || github.ref_name }}
      - name: create environment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_ENVIRONMENT_OPERATION }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/environments/$ENV_NAME  \
            -F "wait_timer=30"
      - name: set environment variables
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_ENVIRONMENT_OPERATION }}
          VARIABLES_FOR_ENVIRONMENTS: ${{ vars.VARIABLES_FOR_ENVIRONMENTS }}
        run: |
          echo "$VARIABLES_FOR_ENVIRONMENTS"  \
          | jq -r 'to_entries|.[]|"
            gh api \\
              --method POST \\
              -H \"Accept: application/vnd.github+json\" \\
              -H \"X-GitHub-Api-Version: 2022-11-28\" \\
              /repos/$GITHUB_REPOSITORY/environments/$ENV_NAME/variables \\
               -f \"name=\(.key)\" -f \"value=\(.value)\"
            "'  \
          | bash -vx
 
