name: Create Environment

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  createEnvironment:
    runs-on: ubuntu-22.04
    steps:
      - run: gh version
