name: Create Environment

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  createEnvironment:
    runs-on: ubuntu-22.04
    steps:
      - run: gh version
      - run: echo -n dev-$(echo "$HEAD_REF" | sha1sum | cut -c1-8) | tee /tmp/envname.txt
        env:
          HEAD_REF: ${{ github.head_ref || github.ref_name }}
      - run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/kaznak/20240614.github-actions-event-test/environments/$(cat /tmp/envname.txt)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_ENVIRONMENT_OPERATION }}
