name: Create Environment

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  createEnvironment:
    runs-on: ubuntu-22.04
    steps:
      - run: gh version
      - name: generate environment name
        run: echo -n dev-$(echo "$HEAD_REF" | sha1sum | cut -c1-8) | tee /tmp/envname.txt
        env:
          HEAD_REF: ${{ github.head_ref || github.ref_name }}
      - name: create environment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_ENVIRONMENT_OPERATION }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_ACTION_REPOSITORY/environments/$(cat /tmp/envname.txt)  \
            -F "wait_timer=30"
      - name: set environment variables
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_ENVIRONMENT_OPERATION }}
          VARIABLES_FOR_ENVIRONMENTS: ${{ vars.VARIABLES_FOR_ENVIRONMENTS }}
        run: |
          echo "$VARIABLES_FOR_ENVIRONMENTS"  \
          | jq 'to_entries|.[]|"
            gh api \\
              --method POST \\
              -H \"Accept: application/vnd.github+json\" \\
              -H \"X-GitHub-Api-Version: 2022-11-28\" \\
              /repos/$GITHUB_ACTION_REPOSITORY/environments/'$(cat /tmp/envname.txt)'/variables \\
               -f \"name=\(.key)\" -f \"value=\(.value)\"
            "'  \
          | bash -vx
 
