name: Delete Environment

on:
  # pull_request_target:
  #   types:
  #     - closed
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: a github token with specific permissions. the default value is github.tokens.
      env-name:
        type: string
        required: true
  workflow_call:
    inputs:
      token:
        type: string
        description: a github token with specific permissions. the default value is github.tokens.
      env-name:
        type: string
        required: true

jobs:
  dump_contexts:
    runs-on: ubuntu-22.04
    steps:
        - run: env
        - name: toJSON(inputs)
          run: echo '${{ toJSON(inputs) }}'
        - name: toJSON(github)
          run: echo '${{ toJSON(github) }}'
        - name: toJSON(env)
          run: echo '${{ toJSON(env) }}'
        - name: toJSON(vars)
          run: echo '${{ toJSON(vars) }}'
        - name: toJSON(secrets)
          run: echo '${{ toJSON(secrets) }}'
        - name: toJSON(job)
          run: echo '${{ toJSON(job) }}'
        - name: toJSON(steps)
          run: echo '${{ toJSON(steps) }}'
        - name: toJSON(runner)
          run: echo '${{ toJSON(runner) }}'
        - name: toJSON(strategy)
          run: echo '${{ toJSON(strategy) }}'
        - name: toJSON(matrix)
          run: echo '${{ toJSON(matrix) }}'
        - name: toJSON(needs)
          run: echo '${{ toJSON(needs) }}'
        - run: gh version

  deleteEnvironment:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ inputs.token || github.token }}
      ENV_NAME: ${{ inputs.env-name }}
    steps:
      - shell: bash
        run: |
          set -x
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/environments/$ENV_NAME
