name: "Trigger: pull_request_target"

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  dumpInfo:
    runs-on: ubuntu-22.04
    steps:
      - env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTIONS: ${{ github.event.action }}
          EVENT_MERGED: ${{ github.event.pull_request.merged }}
          GITHUB_CONTEXT: ${{ toJSON(github)} }}
        run: |
          echo "$GITHUB_CONTEXT"
