name: "Trigger: pull_request"

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  dumpInfo:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          cat <<EOF
          ${{ toJSON(github)} }}
          EOF
        env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTIONS: ${{ github.event.action }}
          EVENT_MERGED: ${{ github.event.pull_request.merged }}
