name: "Trigger: push"

on:
  workflow_dispatch:
  push:

jobs:
  dumpInfo:
    runs-on: ubuntu-22.04
    steps:
      - env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTIONS: ${{ github.event.action }}
          EVENT_MERGED: ${{ github.event.pull_request.merged }}
        run: |
          cat <<EOF
          ${{ toJSON(github) }}
          EOF
