name: "Trigger: push"

on:
  workflow_dispatch:
  push:

jobs:
  dumpInfo:
    runs-on: ubuntu-22.04
    steps:
      - env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTIONS: ${{ github.event.action }}
          EVENT_MERGED: ${{ github.event.pull_request.merged }}
        uses: ./.github/workflows/workflow_call.yaml
        with: {}
