name: "Trigger: push"

on:
  workflow_dispatch:
  push:

jobs:
  dumpInfo0:
    uses: ./.github/workflows/workflow_call.yaml
    with:
      required_default_var: hoge
      required_var: uho

  dumpContext:
    if: false
    runs-on: ubuntu-22.04
    steps:
     - uses: kaznak/gha-dump-context@main

  setupNode:
    uses: ./.github/workflows/setup-node.yaml
