name: "Trigger: release"

on:
  workflow_dispatch:
  release:

jobs:
  dump_info:
    runs-on: ubuntu-22.04
    steps:
      - env:
          EVENT_NAME: ${{ github.event_name }}
          EVENT_ACTIONS: ${{ github.event.action }}
          EVENT_MERGED: ${{ github.event.pull_request.merged }}
        run: |
          cat <<EOF
          ${{ toJSON(github) }}
          EOF

  dump_contexts:
    name: Dump Context Values
    runs-on: ubuntu-22.04
    steps:
        - run: env
        - name: toJSON(inputs)
          run: echo '${{ toJSON(inputs) }}'
        - name: toJSON(github)
          run: echo '${{ toJSON(github) }}'
        - name: toJSON(env)
          run: echo '${{ toJSON(env) }}'
        - name: toJSON(vars)
          run: echo '${{ toJSON(vars) }}'
        - name: toJSON(secrets)
          run: echo '${{ toJSON(secrets) }}'
        - name: toJSON(job)
          run: echo '${{ toJSON(job) }}'
        - name: toJSON(steps)
          run: echo '${{ toJSON(steps) }}'
        - name: toJSON(runner)
          run: echo '${{ toJSON(runner) }}'
        - name: toJSON(strategy)
          run: echo '${{ toJSON(strategy) }}'
        - name: toJSON(matrix)
          run: echo '${{ toJSON(matrix) }}'
        - name: toJSON(needs)
          run: echo '${{ toJSON(needs) }}'
        - run: gh version
