name: "Trigger: workflow_call: dump context"

on:
  workflow_dispatch:

jobs:
  setp-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - run: node -v
    - run: npm -v
