name: "Trigger: workflow_call: dump context"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
        required_default_var:
            description: required variable with default value
            required: true
            default: default value
            type: string
        required_var:
            description: required variable without default value
            required: true
            type: string

jobs:
  dumpInfo:
    runs-on: ubuntu-22.04
    steps:
        - run: env
        - run: echo '${{ toJSON(inputs) }}'
        - run: echo '${{ toJSON(github) }}'
        - run: echo '${{ toJSON(env) }}'
        - run: echo '${{ toJSON(vars) }}'
        - run: echo '${{ toJSON(secrets) }}'
        - run: gh version
