name: "Trigger: workflow_call: dump context"

on:
  workflow_dispatch:
  workflow_call:
    inputs:
        required_default_var:
            description: required variable with default value
            required: true
            default: default value
            type: string
        required_var:
            description: required variable without default value
            required: true
            type: string

jobs:
  dumpInfo:
    runs-on: ubuntu-22.04
    steps:
        - run: env
        - name: toJSON(inputs)
          run: echo '${{ toJSON(inputs) }}'
        - name: toJSON(github)
          run: echo '${{ toJSON(github) }}'
        - name: toJSON(env)
          run: echo '${{ toJSON(env) }}'
        - name: toJSON(vars)
          run: echo '${{ toJSON(vars) }}'
        - name: toJSON(secrets)
          run: echo '${{ toJSON(secrets) }}'
        - name: toJSON(job)
          run: echo '${{ toJSON(job) }}'
        - name: toJSON(steps)
          run: echo '${{ toJSON(steps) }}'
        - name: toJSON(runner)
          run: echo '${{ toJSON(runner) }}'
        - name: toJSON(strategy)
          run: echo '${{ toJSON(strategy) }}'
        - name: toJSON(matrix)
          run: echo '${{ toJSON(matrix) }}'
        - name: toJSON(needs)
          run: echo '${{ toJSON(needs) }}'
        - run: gh version
